### ISSUE TITLE
diary Branch löschen

### ISSUE THREAD

**Issue by JonasFhInfo** [JonasFhInfo/SWPM#24]
Der Branch ist etwas ausgearted.
Dies liegt daran, dass ich die Pull-Requests davon immer gesquashed habe, also alle "Veränderungen" in einen neuen commit gedrückt habe. Und da bei einem merge alle unbekannten commits übertragen werden, sind es mitlerweile 20+ commits die in den master wollen.
zu sehen: https://github.com/JonasFhInfo/SWPM/commit/42ce70f05ef3ecfa58c114e94a68502974a0c9e1
Und die Liste wird imemr länger.

Die sauerbste Lösung ist das löschen & neu aufmachen des Branches.
Führt eure letzten Änderungen noch durch & löscht den Branch danach bitte.

**Comment by JonasFhInfo** [comment]
Jep, wenn viddie auch nichts mehr hat.

**Comment by viddie** [comment]
Jo, werde ich nachher machen
